PREFIX base:        <http://imce.jpl.nasa.gov/foundation/base#>
PREFIX mission:     <http://imce.jpl.nasa.gov/foundation/mission#>
PREFIX structure:   <http://opencaesar.io/open-source-rover/vocabulary/structure#>
PREFIX rdfs:        <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?subsystem ?assembly
WHERE {


	?c1 structure:hasAssembly ?c2 ;
		base:hasIdentifier ?c1_id ;
		base:hasCanonicalName ?c1_name ;

    BIND(STRAFTER(STR(?c1), "#") AS ?subsystem) .
    BIND(STRAFTER(STR(?c2), "#") AS ?assembly) .

}
ORDER BY ?c1_id